In [18]:
import pandas as pd

In [19]:
fl = 'data/consolidated/iv_by_post.csv'

In [20]:
iv = pd.read_csv(fl, delimiter="|", dtype={'Quantity': int})

In [21]:
iv

,Post,VisaClass,Quantity,VisaType,Year,Month,Category,SubCategory,Description
0,abidjan,cr1,9,IV,2017,April,Immediate Relatives,General,Spouse of U.S. citizen (conditional status) 20...
1,abidjan,dv1,42,IV,2017,April,Other Numerically Limited Categories,Diversity Immigrants,Diversity Immigrant 203(c)
2,abidjan,dv2,18,IV,2017,April,Other Numerically Limited Categories,Diversity Immigrants,Spouse of DV1 203(d) & 203(c)
3,abidjan,dv3,4,IV,2017,April,Other Numerically Limited Categories,Diversity Immigrants,Child of DV1 203(d) & 203(c)
4,abidjan,f11,5,IV,2017,April,Family-Sponsored Preferences,Family 1st Preference,Unmarried son or daughter of U.S. citizen 203(...
...,...,...,...,...,...,...,...,...,...
79867,zagreb,f31,1,IV,2019,September,Family-Sponsored Preferences,Family 3rd Preference,Married son or daughter of U.S. citizen 203(a)(3)
79868,zagreb,f32,1,IV,2019,September,Family-Sponsored Preferences,Family 3rd Preference,Spouse of F31 203(d) & 203(a)(3)
79869,zagreb,f33,2,IV,2019,September,Family-Sponsored Preferences,Family 3rd Preference,Child of F31 203(d) & 203(a)(3)
79870,zagreb,f41,1,IV,2019,September,Family-Sponsored Preferences,Family 4th Preference,Brother or sister of U.S. citizen at least 21 ...
79871,zagreb,f42,1,IV,2019,September,Family-Sponsored Preferences,Family 4th Preference,Spouse of F41 203(d) & 203(a)(4)

In [22]:
iv.groupby('Post').head(3).sort_values(['Quantity'], ascending=False)

,Post,VisaClass,Quantity,VisaType,Year,Month,Category,SubCategory,Description
543,ciudad juarez,cr1,339,IV,2017,April,Immediate Relatives,General,Spouse of U.S. citizen (conditional status) 20...
1920,santo domingo,cr1,270,IV,2017,April,Immediate Relatives,General,Spouse of U.S. citizen (conditional status) 20...
70,addis ababa,dv1,246,IV,2017,April,Other Numerically Limited Categories,Diversity Immigrants,Diversity Immigrant 203(c)
1056,kathmandu,dv1,178,IV,2017,April,Other Numerically Limited Categories,Diversity Immigrants,Diversity Immigrant 203(c)
2267,yaounde,dv1,140,IV,2017,April,Other Numerically Limited Categories,Diversity Immigrants,Diversity Immigrant 203(c)
...,...,...,...,...,...,...,...,...,...
536,chisinau,cr1,1,IV,2017,April,Immediate Relatives,General,Spouse of U.S. citizen (conditional status) 20...
1748,port-au-prince,ew3,1,IV,2017,April,Employment-Based Preferences,"Employment 3rd Preference (Skilled Workers, Pr...",Other worker (subgroup numerical limit) 203(b)...
1772,prague,cr1,1,IV,2017,April,Immediate Relatives,General,Spouse of U.S. citizen (conditional status) 20...
1809,riga,f41,1,IV,2017,April,Family-Sponsored Preferences,Family 4th Preference,Brother or sister of U.S. citizen at least 21 ...
19981,kuwait city,cr1,0,IV,2019,December,Immediate Relatives,General,Spouse of U.S. citizen (conditional status) 20...

In [23]:
iv.groupby('Post').sum().sort_values(['Quantity'], ascending=False)

                  Quantity     Year
Post
ciudad juarez       197924  2556923
santo domingo       126755  1921170
ho chi minh city     85569  2284462
guangzhou            82032  3065409
manila               77746  2621443
...                    ...      ...
panama city             37    30285
lisbon                  27    36319
port moresby            20    36333
belize                  11    12114
copenhagen               3     4035

[147 rows x 2 columns]

In [24]:
iv[iv.Post =='santo domingo']

,Post,VisaClass,Quantity,VisaType,Year,Month,Category,SubCategory,Description
1920,santo domingo,cr1,270,IV,2017,April,Immediate Relatives,General,Spouse of U.S. citizen (conditional status) 20...
1921,santo domingo,cr2,95,IV,2017,April,Immediate Relatives,General,Child of U.S. citizen (conditional status) 201...
1922,santo domingo,e23,1,IV,2017,April,Employment-Based Preferences,Employment 2nd Preference (Professionals Holdi...,Child of E21 203(d) & 203(b)(2)
1923,santo domingo,e31,1,IV,2017,April,Employment-Based Preferences,"Employment 3rd Preference (Skilled Workers, Pr...",Skilled worker 203(b)(3)(A)(i).
1924,santo domingo,e35,1,IV,2017,April,Employment-Based Preferences,"Employment 3rd Preference (Skilled Workers, Pr...",Child of E31 or E32 203(d) & 203(b)(3)(A)(i) &...
...,...,...,...,...,...,...,...,...,...
79539,santo domingo,ir2,55,IV,2019,September,Immediate Relatives,General,Child of U.S. citizen 201(b)
79540,santo domingo,ir5,80,IV,2019,September,Immediate Relatives,General,Parent of U.S. citizen at least 21 years of ag...
79541,santo domingo,iw1,1,IV,2019,September,Immediate Relatives,General,Certain spouses of deceased U.S. citizens 201(b)
79542,santo domingo,iw2,1,IV,2019,September,Immediate Relatives,General,Child of IW-1 201(b)
79543,santo domingo,sb1,3,IV,2019,September,Special Immigrants,General,Returning resident 101(a)(27)(A)

In [27]:
iv.loc[iv.Post=='santo domingo', ['Post','VisaClass', 'Quantity','Description']].groupby(['VisaClass', 'Description']).sum().sort_values(['Quantity'], ascending=False).head(50)

                                                              Quantity
VisaClass Description
f25       Child of F24 203(d) & 203(a)(2)(B)                     14563
ir5       Parent of U.S. citizen at least 21 years of age...     13039
ir2       Child of U.S. citizen 201(b)                           11021
f24       Unmarried son or daughter of lawful permanent r...     10871
fx1       Spouse of lawful permanent resident 202(a)(4)(A...      9862
cr1       Spouse of U.S. citizen (conditional status) 201...      9716
ir1       Spouse of U.S. citizen 201(b)                           8647
fx3       Child of FX1 or FX2 202(a)(4)(A) & 203(a)(2)(A)...      8486
f12       Child of F11 203(d) & 203(a)(1)                         6284
f21       Spouse of lawful permanent resident 203(a)(2)(A)        5712
f11       Unmarried son or daughter of U.S. citizen 203(a...      5488
fx2       Child of lawful permanent resident 202(a)(4)(A)...      4795
f23       Child of F21 or F22 203(d) & 203(a)(2)(A)               3522
cr2       Child of U.S. citizen (conditional status) 201(...      3376
f43       Child of F41 203(d) & 203(a)(4)                         2730
f22       Child of lawful permanent resident 203(a)(2)(A)         2515
f41       Brother or sister of U.S. citizen at least 21 y...      2411
f42       Spouse of F41 203(d) & 203(a)(4)                        1215
f33       Child of F31 203(d) & 203(a)(3)                          828
f31       Married son or daughter of U.S. citizen 203(a)(3)        542
f32       Spouse of F31 203(d) & 203(a)(3)                         508
sb1       Returning resident 101(a)(27)(A)                         193
ib3       Child of IB-1 204(a)(1)(A)(iii)                           98
iw1       Certain spouses of deceased U.S. citizens 201(b)          90
iw2       Child of IW-1 201(b)                                      48
se3       Child of SE1 101(a)(27)(D) & 203(b)(4)                    23
ih3       Child adopted abroad by U.S. citizen under Hagu...        21
e35       Child of E31 or E32 203(d) & 203(b)(3)(A)(i) & ...        20
e31       Skilled worker 203(b)(3)(A)(i).                           18
se1       Certain employees or former employees of the U....        11
se2       Spouse of SE1 101(a)(27)(D) & 203(b)(4)                   10
e34       Spouse of E31 or E32 203(d) & 203(b)(3)(A)(i) &...         9
ib1       Self-petition spouse of U.S. citizen 204(a)(1)(...         7
i51       Investor pilot program, targeted area 203(b)(5)            7
b23       Child of B21 or B22 203(d) & 204(a)(1)(B)(ii)              7
ew3       Other worker (subgroup numerical limit) 203(b)(...         6
i52       Spouse of I51 203(d) & 203(b)(5)                           6
i53       Child of I51 203(d) & 203(b)(5)                            6
e23       Child of E21 203(d) & 203(b)(2)                            4
ib2       Self-petition child of U.S. citizen 204(a)(1)(A...         4
bx2       Self-petition child of lawful permanent residen...         3
ew4       Spouse of EW3 203(d) & 203(b)(3)(A)(iii)                   3
e21       Professional holding advanced degree or alien o...         3
dv3       Child of DV1 203(d) & 203(c)                               3
e11       Person with extraordinary ability in the scienc...         2
bx3       Child of BX1 or BX2 204(a)(1)(B)(ii) & 203(d)              2
dv1       Diversity Immigrant 203(c)                                 2
su3       Child of U1 INA 245(m)(3) & INA 101(a)(15)(U)(ii)          2
e15       Child of E11, E12, or E13 203(d) & 203(b)(1)(A)...         2
e22       Spouse of E21 203(d) & 203(b)(2)                           2